
const rowValues = [
    {
        image: 'https://lh3.googleusercontent.com/ogw/ADea4I59UnydkzAp8SCu46TwlHECQMXRszLOX7ZyOL02=s32-c-mo',
        sku: 3336,
        productName: "Product Name",
        status: "online",
        stock: "In-stock",
        price: "SR 350",
        category: "Flowers",
        date: "28/2/2021",
    },
    {
        image: 'https://lh3.googleusercontent.com/ogw/ADea4I59UnydkzAp8SCu46TwlHECQMXRszLOX7ZyOL02=s32-c-mo',
        sku: 33346,
        productName: "Product Name",
        status: "pending",
        stock: "In-stock",
        price: "SR 350",
        category: "Flowers",
        date: "28/2/2021",
    },
    {
        image: 'https://lh3.googleusercontent.com/ogw/ADea4I59UnydkzAp8SCu46TwlHECQMXRszLOX7ZyOL02=s32-c-mo',
        sku: 34346,
        productName: "Product Name",
        status: "offine",
        stock: "In-stock",
        price: "SR 350",
        category: "Flowers",
        date: "28/2/2021",
    },
    {
        image: '',
        sku: 3432346,
        productName: "Product Name",
        status: "offine",
        stock: "In-stock",
        price: "SR 350",
        category: "Flowers",
        date: "28/2/2021",
    },
    {
        image: '',
        sku: 3432346,
        productName: "Product Name",
        status: "offine",
        stock: "In-stock",
        price: "SR 350",
        category: "Flowers",
        date: "28/2/2021",
    },
    {
        image: '',
        sku: 3432346,
        productName: "Product Name",
        status: "offine",
        stock: "In-stock",
        price: "SR 350",
        category: "Flowers",
        date: "28/2/2021",
    },
    {
        image: '',
        sku: 3432346,
        productName: "Product Name",
        status: "offine",
        stock: "In-stock",
        price: "SR 350",
        category: "Flowers",
        date: "28/2/2021",
    },
]
export default rowValues;